version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog